name: "Gitleaks Scan"

on:
  schedule:
    - cron: "*/1 * * * *" # Run every minute

jobs:
  gitleaks_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          sudo apt update
          sudo apt install -y gitleaks
      - name: Gitleaks Scan
        run: |
          gitleaks --repo . --verbose 
